/**
 * Vendors Bricolage Grotesque + Inter into assets/fonts/ at build time.
 *
 * Self-hosted rather than linked from Google Fonts: this guide gets used on a
 * phone on Tokyo transit, and a render-blocking third-party stylesheet is one
 * more thing that can be slow or blocked. Same principle as the photos.
 *
 * Usage: node scripts/vendor-fonts.mjs
 */
import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const FONT_DIR = path.join(ROOT, 'assets', 'fonts');

// A browser UA is required, otherwise Google Fonts serves legacy ttf.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Bricolage+Grotesque:opsz,wght@12..96,400..800' +
  '&family=Inter:wght@400..700' +
  '&display=swap';

// Latin only - this guide is English, and skipping the other subsets keeps the
// download small.
const KEEP_SUBSETS = ['latin', 'latin-ext'];

await mkdir(FONT_DIR, { recursive: true });

const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then((r) => {
  if (!r.ok) throw new Error(`fonts css ${r.status}`);
  return r.text();
});

// Google annotates each @font-face block with a /* subset */ comment.
const blocks = css.split('/*').filter(Boolean);
const kept = [];

for (const block of blocks) {
  const subset = block.slice(0, block.indexOf('*/')).trim();
  if (!KEEP_SUBSETS.includes(subset)) continue;

  const face = block.slice(block.indexOf('*/') + 2);
  const url = face.match(/url\((https:\/\/[^)]+)\)/)?.[1];
  if (!url) continue;

  const family = face.match(/font-family:\s*'([^']+)'/)?.[1] ?? 'font';
  const slug = `${family.toLowerCase().replace(/\s+/g, '-')}-${subset}.woff2`;

  const bytes = Buffer.from(
    await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => {
      if (!r.ok) throw new Error(`font ${r.status} ${url}`);
      return r.arrayBuffer();
    }),
  );
  await writeFile(path.join(FONT_DIR, slug), bytes);
  console.log(`${slug} (${Math.round(bytes.length / 1024)}KB)`);

  kept.push(face.replace(/url\(https:\/\/[^)]+\)/, `url(./${slug})`).trim());
}

const header = `/* Generated by scripts/vendor-fonts.mjs - do not edit by hand.
   Bricolage Grotesque and Inter, both under the SIL Open Font License 1.1. */\n\n`;
await writeFile(path.join(FONT_DIR, 'fonts.css'), header + kept.join('\n\n') + '\n');
console.log(`\nwrote ${kept.length} @font-face rules -> assets/fonts/fonts.css`);
